version: '3'

tasks:
  up:
    cmds:
      - COMPOSE_BAKE=true docker compose -f .docker/infra/compose.yml up -d --build --force-recreate
      - COMPOSE_BAKE=true docker compose -f .docker/app/compose.yml up --build --force-recreate --watch
    silent: true
  down:
    cmds:
      - docker compose -f .docker/infra/compose.yml  down
      - docker compose -f .docker/app/compose.yml down
    silent: true