services:
  gitlab-web:
    image: 'iabsdocker/gitlab-ce:latest'
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
#        nginx['listen_port'] = 8000
#        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "8000:80"
#      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
    env_file:
      - ../../.env
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    depends_on:
      - gitlab-web
    volumes:
      - ../conf/config.toml:/etc/gitlab-runner/config.toml
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  gitlab_config:
  gitlab_data:
